### ISSUE TITLE
Идеи по улучшению библиотеки

### ISSUE THREAD

**Issue by DavyJohnes** [vitalets/yc-serverless-live-debug-original#2]
1. Точно ли нужно два гейтвея? Можно же сделать один и он сможет выполнять и функции хэндлера WS и прокси до stub функции
2. Гейтвей обрабатывает `WS CONNECT`, но не обрабатывает `WS DISCONNECT`. Разве не нужно удалять из базы запись, когда клиент отсоединился?
3. Для отправки собщения в ws connection использовать `yandex cloud nodejs-sdk`
4. Реализовать библиотеку в виде подключаемой библиотеки. Как мне это видится:
   - Пользователь устанавливает себе пакет `npm i -D yc-serverless-live-debug`
   - Пользователь формирует в корне своего проекта конфигурационный файл `sls-live-debug.jso`, в котором описывает все нужные параметры
   - Пользователь запускает `npx yc-serverless-debug` и все начинает магическим образом работать.

Подозреваю что в предлагаемой реализации не получится использовать terraform в таком виде, поэтому предлагаю переехать на terraform CDK, позволяющий выполнять все те же самые функции из кода. Заодного и можно будет избавиться от запроса от пользователя STUB_ID\WS_URL, поскольку мы будем сами их знать в коде.

5. Реализовать дебаг сразу нескольких функций. Можно в конфиг из пункта 4 записывать маппинг вида "function_name -> function_handler_path` таким образом, что `live-debug` при создании гейтвея будет формировать пути на основе `function_name` из конфига, а локальная библиотека по заголовку от stub api-gateway понимать какой `handler` нужно зареквайрить и выполнить.

**Comment by vitalets** [comment]
Привет! Спасибо за фидбэк.

> 1. Точно ли нужно два гейтвея? Можно же сделать один и он сможет выполнять и функции хэндлера WS и прокси до stub функции

Я экспериментировал с одним гейтвеем, там получается циклическая зависимость в терраформ: гейтвей ссылается на функцию, а функции нужен адрес гейтвея для коннекта. Можно сохранять адрес гейтвея в базе при коннекте клиента (т.к. клиент знает гейтвей), а в функции забирать его динамически вместе с connectionId. Но потом я еще подумал, что если у меня есть функция с каким-то своим гейтвеем и я хочу тестить именно такой сетап, то затаскивать в этот гейтвей обработку вебсокетов как-то не очень хорошо. Поэтому решил оставить два: пусть вебсокетный гейтвей сам по себе живет, а к функции можно другой гейтвей настраивать максимально похожий на продакшн.

> 2. Гейтвей обрабатывает WS CONNECT, но не обрабатывает WS DISCONNECT. Разве не нужно удалять из базы запись, когда клиент отсоединился?

Делал по принципу "минимизируем ~деньги~ количество вызовов функции". Если клиент отключился, то функция просто не сможет отправить ему запрос и выведет сообщение, что нет подключенных клиентов.

> 3. Для отправки собщения в ws connection использовать yandex cloud nodejs-sdk

Окей, сделаем

> 4. Реализовать библиотеку в виде подключаемой библиотеки.

Согласен, будет удобнее. Конфиг сделаю, это как раз и для дебага нескольких функций полезно будет. Вопрос - 
если у меня handler на тайпскрипте, то запуская `npx yc-serverless-debug` мне нужно будет как-то откомпилировать этот handler? Не совсем понимаю, как тут правильнее сделать.
```js
// live-debug.config.js
export default {
  function1: './src/handler1.ts',
  function2: './src/handler2.ts',
};
```

> Подозреваю что в предлагаемой реализации не получится использовать terraform в таком виде, поэтому предлагаю переехать на terraform CDK, позволяющий выполнять все те же самые функции из кода. Заодного и можно будет избавиться от запроса от пользователя STUB_ID\WS_URL, поскольку мы будем сами их знать в коде.

Ок, я попробую. А как оно тогда будет разворачиваться? Например, я установил `npm i @yandex-cloud/live-debug`. Дальше надо запустить что-то типа `npx live-debug deploy`? И про STUB_ID\WS_URL - имеешь ввиду сохранить их в файлик типа `.live-debug/config` или Terraform CDK позволяет потом вытащить все данные по ресурсам из стейта?

> Реализовать дебаг сразу нескольких функций.

Сейчас маппинг запросов предполагается [по id функции](https://github.com/vitalets/yc-serverless-live-debug/blob/8fa20f640571c70f36a694ab914e9cc9e3eb7269/src/stub.ts#L35). Если используем имя, тогда как стаб его узнает (в context прилетает только id функции)? Вытащить из данных от гейтвея (`requestContext.apiGateway.operationContext`)? А если пользователь будет все-таки свой гейтвей использовать?
Набросал пример гейтвея для нескольких функций:
```yml
paths:
  /function-1/{path+}:
    x-yc-apigateway-any-method:
    ...
      x-yc-apigateway-integration:
     ...
  /function-2/{path+}:
    x-yc-apigateway-any-method:
    ...
      x-yc-apigateway-integration:
     ...
```

@DavyJohnes @kvikuz

**Comment by DavyJohnes** [comment]
> Согласен, будет удобнее. Конфиг сделаю, это как раз и для дебага нескольких функций полезно будет. Вопрос -
если у меня handler на тайпскрипте, то запуская npx yc-serverless-debug мне нужно будет как-то откомпилировать этот handler? Не совсем понимаю, как тут правильнее сделать.

`ts-node` позволяет зареквайрить ts в своем коде.

> Дальше надо запустить что-то типа npx live-debug deploy?

**Comment by DavyJohnes** [comment]
> Согласен, будет удобнее. Конфиг сделаю, это как раз и для дебага нескольких функций полезно будет. Вопрос -
если у меня handler на тайпскрипте, то запуская npx yc-serverless-debug мне нужно будет как-то откомпилировать этот handler? Не совсем понимаю, как тут правильнее сделать.

`ts-node` позволяет зареквайрить ts в своем коде.

> Дальше надо запустить что-то типа npx live-debug deploy?

В моей голове было так: команда для запуска одна: `npx live-debug` при первом и последующих запусках она всегда сначала запускает создание нужно инфраструктуры с помощью TF CDK. Так как состояние инфраструктуры сохранено в стейте CDK, то последующие кроме первого запуска не будут занимать много времени. В тоже время сильно упрощается интерфейс использовани, пользователю инструменты не нужно думать о том, чтобы создать\обновить инфраструктуру, все будет сделано автоматически при каждом запуске.

> Terraform CDK позволяет потом вытащить все данные по ресурсам из стейта?

Да, я про этот вариант.

> Вытащить из данных от гейтвея (requestContext.apiGateway.operationContext)?

Да, почему нет?

> А если пользователь будет все-таки свой гейтвей использовать?

Не очень понял что значит "свой гейтвей"?

> гейтвей ссылается на функцию, а функции нужен адрес гейтвея для коннекта. 

Можно тут подробнее, пожалуйста? Я не очень понимаю зачем функции знать адрес гейтвея.

**Comment by vitalets** [comment]
По предыдущим пунктам ок!
Насчет гейтвея:

> Можно тут подробнее, пожалуйста? Я не очень понимаю зачем функции знать адрес гейтвея.

Он нужен функции, чтобы знать [куда коннектиться вебсокетом](https://github.com/vitalets/yc-serverless-live-debug/blob/8fa20f640571c70f36a694ab914e9cc9e3eb7269/src/stub.ts#L76). Если класть его в переменные окружения, то адрес нужно знать до создания функции - а это приводит к циклической зависимости, т.к. гейтвей создается после функции, чтобы уметь ее вызвать (это все в случае единого гейтвея для вебсокетов и для вызова функции).

> Не очень понял что значит "свой гейтвей"?

Я вот про что: допустим у меня есть большое приложение со своим развесистым гейтвеем и я хочу подебажить одну из функций, которая вызывается через этот гейтвей. Какой процесс мы тут предложим? Скорее всего пользователь захочет вызывать локальный код через тот же гейтвей, чтобы туда добавились все те же заголовки, контекст, возможно данные авторайзера итп. Тогда он должен либо создать копию гейтвея, где функция заменена на стаб, либо создать в том же гейтвее отдельный роут на стаб. Но в любом случае это не тот гейтвей, который мы создаем - поэтому я назвал его "свой" (свой с т.з. пользователя)

В целом я только за сокращение сущностей. Циклическую зависимость можно обойти, если добавить в ydb колонку wsUrl, которую будет заполнять клиент при коннекте. Я так пробовал - оно работает. Тогда можем оставить один гейтвей.

**Comment by DavyJohnes** [comment]
> Я вот про что: допустим у меня есть большое приложение со своим развесистым гейтвеем и я хочу подебажить одну из функций, которая вызывается через этот гейтвей. Какой процесс мы тут предложим? Скорее всего пользователь захочет вызывать локальный код через тот же гейтвей, чтобы туда добавились все те же заголовки, контекст, возможно данные авторайзера итп. Тогда он должен либо создать копию гейтвея, где функция заменена на стаб, либо создать в том же гейтвее отдельный роут на стаб. Но в любом случае это не тот гейтвей, который мы создаем - поэтому я назвал его "свой" (свой с т.з. пользователя)

Я бы предложил пока об этом не задумываться ради упрощения конструкции инструмента. У нас первостепенная цель - это дать возможность изолированно дебажить функцию (набор функций) в локальном окружении так, как будто она развернута в облаке.

> Циклическую зависимость можно обойти, если добавить в ydb колонку wsUrl, которую будет заполнять клиент при коннекте.

Пока сам не понял, что в этом плохого, но ведь стаб функция всегда знает URL, по которому на нее пришли (это URL гейтвея, который в предлагаемой схеме единственный), а значит она может на него же и приконнектиться, соблюдая внутренний контракт (URL коннекта, скажем `/ws`).

**Comment by vitalets** [comment]
> Я бы предложил пока об этом не задумываться ради упрощения конструкции инструмента. У нас первостепенная цель - это дать возможность изолированно дебажить функцию (набор функций) в локальном окружении так, как будто она развернута в облаке.

Окей.

> Пока сам не понял, что в этом плохого, но ведь стаб функция всегда знает URL, по которому на нее пришли (это URL гейтвея, который в предлагаемой схеме единственный), а значит она может на него же и приконнектиться, соблюдая внутренний контракт (URL коннекта, скажем `/ws`).

Тогда предлагаю все-таки сделать через колонку в бд. Это недорого, зато функция становится независимой от гейтвея, через который к ней пришли. Потенциально это позволит тестить любые триггеры, например ymq. Ну и возможность проверить через отдельный гетвей точно не будет лишней.

По вопросом все обсудили, в выходные посмотрю :)

**Comment by vitalets** [comment]
Новая версия со всеми улучшениями готова! Описал все в ридми и опубликовал в npm под собой для теста. 
Ваня, Витя проверьте как оно все разворачивается.

@DavyJohnes @kvikuz

**Comment by DavyJohnes** [comment]
Проверил, работает отлично! Интерфейс взаимодействия с тулзой теперь удобный, как по мне. Отличная работа, спасибо!
